{{- range $tls := .Values.ingress.tls -}}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ .secretName }}
  namespace: {{ $.Release.Namespace }}
  labels:
{{ include "webhook-broadcaster.helm-labels" $ | indent 4 }}
spec:
  acme:
    config:
      - dns01:
          provider: optiopay-route53
        domains:
{{ toYaml .hosts | indent 10 }}
  dnsNames:
{{ toYaml .hosts | indent 4 }}
  issuerRef:
    kind: ClusterIssuer
    name: cert-manager-extras-letsencrypt-production
  secretName: {{ .secretName }}
---
{{- end }}
