apiVersion: v1
kind: Secret
metadata:
  name: {{ include "webhook-broadcaster.fullname" . }}
  labels:
{{ include "webhook-broadcaster.helm-labels" . | indent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.envSecrets }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
  {{- range  .Values.secretVolumes }}
    {{- range .files }}
  {{ .name }}: {{ .value | b64enc | quote }}
    {{- end }}
  {{- end }}
